// <auto-generated />
using System;
using FitRos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitRos.Infrastructure.Migrations
{
    [DbContext(typeof(FitRosDbContext))]
    partial class FitRosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitRos.Domain.Entities.Training.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("RepsAchieved")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightUsed")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseSet");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkoutRoutines");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutRoutineExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedReps")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedRestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedSets")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkoutRoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRoutineId");

                    b.ToTable("WorkoutRoutineExercise");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutineNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoutineVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.ExerciseSet", b =>
                {
                    b.HasOne("FitRos.Domain.Entities.Training.WorkoutSession", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutRoutineExercise", b =>
                {
                    b.HasOne("FitRos.Domain.Entities.Training.WorkoutRoutine", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutRoutineId");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutRoutine", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitRos.Domain.Entities.Training.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
