using FitRos.Domain.Entities.Training;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FitRos.Infrastructure.Persistence.Configurations;

public class WorkoutRoutineExerciseConfiguration
    : IEntityTypeConfiguration<WorkoutRoutineExercise>
{
    public void Configure(EntityTypeBuilder<WorkoutRoutineExercise> builder)
    {
        builder.ToTable("WorkoutRoutineExercises");

        builder.HasKey(x => x.Id);

        // the domain entity has a private setter for Id, so we need to tell EF Core
        // that the value will be generated by the application and not by the database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        builder.Property(x => x.WorkoutRoutineId)
            .IsRequired();

        builder.Property(x => x.ExerciseId)
            .IsRequired();

        builder.Property(x => x.Order)
            .IsRequired();

        builder.Property(x => x.SuggestedSets)
            .IsRequired();

        builder.Property(x => x.SuggestedReps)
            .IsRequired();

        builder.Property(x => x.SuggestedRestSeconds)
            .IsRequired();
        builder.HasIndex(x => new { x.WorkoutRoutineId, x.ExerciseId })
       .IsUnique();

        builder.HasIndex(x => new { x.WorkoutRoutineId, x.Order })
               .IsUnique();
    
}
}
